services:
  node-rest:
    container_name: node-rest
    image: node-rest
    build: ./node-rest
    restart: always
    ports:
      - "8090:8080"
  go-rest:
    container_name: go-rest
    image: go-rest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - WEATHER_BASE_URL=http://node-rest:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
  spring-rest-virtual:
    container_name: spring-rest-virtual
    image: spring-rest-virtual
    restart: always
    ports:
      - "8081:8080"
    environment:
      - WEATHER_BASE_URL=http://node-rest:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
  spring-rest-platform:
    container_name: spring-rest-platform
    image: spring-rest-platform
    restart: always
    ports:
      - "8082:8080"
    environment:
      - WEATHER_BASE_URL=http://node-rest:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G