services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server data --console-address ":9001"
  go-rest:
    container_name: go-rest
    image: go-rest
    #build: ./go-rest/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - WEATHER_BASE_URL=http://minio:9000/1132ee15-24fb-46ab-be31-8e698d76f017
    mem_limit: 1G
    cpus: "1"
  spring-rest-virtual:
    container_name: spring-rest-virtual
    image: spring-rest-virtual
    #build: ./spring-rest/
    restart: always
    ports:
      - "8081:8080"
    environment:
      - WEATHER_BASE_URL=http://minio:9000/1132ee15-24fb-46ab-be31-8e698d76f017
    mem_limit: 1G
    cpus: "1"