services:
  node-rest:
    build: ./node-rest
    restart: always
    ports:
      - "8090:8080"
  go-rest:
    build: ./go-rest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - WEATHER_BASE_URL=http://node-rest:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  spring-rest:
    build: ./spring-rest
    restart: always
    ports:
      - "8081:8080"
    environment:
      - WEATHER_BASE_URL=http://node-rest:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M